package com.example.android.maximfialko.room;

import android.util.Log;

import com.example.android.maximfialko.data.NewsItem;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Locale;

public class MapperDbToNewsItem {
    public static List<NewsItem> map(List<NewsItemDB> listDb) {

        final List<NewsItem> list = new ArrayList<>();

        for (NewsItemDB item_db : listDb) {
            list.add(
                    new NewsItem(
                            item_db.getId(),                             //id - autogenerated by Room
                            item_db.getTitle(),                          //title
                            item_db.getImageUrl(),                       //imageUrl
                            item_db.getCategory(),                       //category
                            item_db.getPublishDate(),  //publishDate
                            item_db.getPreviewText(),                    //textPreview
                            item_db.getTextUrl()                         //textUrl
                    )
            );
//            Log.d("room","CONVERTED DB -> NewsItems");
//            Log.d("room", "________________date from db: " + item_db.getPublishDate());
        }
        return list;
    }
}

